services:
  config:
    image: ghcr.io/amalpotra/menty-config:main

  registry:
    image: ghcr.io/amalpotra/menty-registry:main
    expose:
      - 8761
    depends_on:
      config:
        condition: service_healthy

  gateway:
    image: ghcr.io/amalpotra/menty-gateway:main
    ports:
      - 8080:8760
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy

  poll:
    image: ghcr.io/amalpotra/menty-poll:main
    expose:
      - 8762
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy
