services:
  config:
    image: ghcr.io/amalpotra/menty-config:main

  registry:
    image: ghcr.io/amalpotra/menty-registry:main
    expose:
      - 8761
    depends_on:
      config:
        condition: service_healthy

  gateway:
    image: ghcr.io/amalpotra/menty-gateway:main
    ports:
      - 8080:8760
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy

  poll:
    image: ghcr.io/amalpotra/menty-poll:main
    expose:
      - 8762
    depends_on:
      config:
        condition: service_healthy
      registry:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
