name: Build and publish

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build and test with Gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: |
            build
            --parallel
      - name: Upload jars
        uses: actions/upload-artifact@v3
        with:
          name: jars
          retention-days: 1
          path: |
            */build/libs/*.jar
            !build-logic

  docker:
    runs-on: ubuntu-latest
    needs: gradle
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    strategy:
      matrix:
        include:
          - name: config
            image: ghcr.io/amalpotra/menty-config
          - name: registry
            image: ghcr.io/amalpotra/menty-registry
          - name: gateway
            image: ghcr.io/amalpotra/menty-gateway
          - name: poll
            image: ghcr.io/amalpotra/menty-poll
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download jars
        uses: actions/download-artifact@v3
        with:
          name: jars
      - name: Login to Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        if: github.event_name != 'pull_request'
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push Docker image for ${{ matrix.name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
